# Makefile: A standard Makefile for command/c/main.c

CFLAGS=-g -std=gnu99 -Wall -Wno-parentheses
#LDFLAGS=
LDLIBS=

all : main
main: main.o
run: main
	./main

clean:
	/bin/rm -rf main main.o
# END OF FILE
